kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: dev-panel-bluconsole-com
  namespace: default
spec:
  tls:
    - hosts:
      - dev-panel.bluconsole.com
      secretName: bluconsole-tls
  rules:
    - host: dev-panel.bluconsole.com
      http:
        paths:
          - path: /
            backend:
              serviceName: dev-frontend
              servicePort: 80
